name: "过期 Issue 处理"

on:
  workflow_dispatch:
  schedule:
    # 每天 23:40 运行
    - cron: "40 23 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'miniocean404-rust'
    steps:
      - uses: actions/stale@v9
        name: "关闭没有反馈的过期问题"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-labels: "需要更多的信息"
          close-issue-message: "这个问题已经自动关闭，因为它一个月没有收到任何活动，也没有反馈信息来调查。如果你认为这是意外关闭的，请留下评论。如果您遇到类似的问题，请打开带有反馈的新问题。谢谢！"
          days-before-issue-close: 1
          days-before-issue-stale: 30
          days-before-pr-close: -1
          days-before-pr-stale: -1
          exempt-issue-labels: "blocked,must,should,keep"
          operations-per-run: 300
